services:
    mongodb:
        image: bitnami/mongodb:latest
        container_name: "mongodb"
        environment:
          MONGODB_USERNAME: root
          MONGODB_PASSWORD: root_pass
          MONGODB_DATABASE: my_db
        volumes:
          - mongodb_data_container:/data/db
        ports:
            - 27017:27017

volumes:
  mongodb_data_container:
